spring.application.name=server
spring.datasource.url=jdbc:postgresql://localhost:5432/scholarsync
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
spring.security.oauth2.client.registration.google.client-id=63087875898-erguna3m9pbnfh2anj52vu3k1hif6h0e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/v1/google-auth/login